services:
  - type: web
    name: ipo-web-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ipo-notify.py"
    envVars:
      - key: FLASK_ENV
        value: production